from flask import Flask, request, jsonify, session, request, redirect
from flask_cors import CORS
import random
import qrcode

from config import API_KEY, DB_URL, ACCOUNT_NAME

from ibmcloudant.cloudant_v1 import CloudantV1, Document
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator

from cloudant.client import Cloudant


def connectDB():
    connection = Cloudant.iam(ACCOUNT_NAME, API_KEY, connect=True)
    print("DATABASE CONNECTED")

    return connection


app = Flask(__name__)
app.config['SECRET_KEY'] = '9a63e9b6b22e11eabdab2816a84a348cc0491ea4b22e11eaac1f2816a84a348cc49ad6abb22e11eab6112816a84a348c'
CORS(app)

connection = connectDB()


@app.route('/')
def homepage():
    '''
    my_database = client.create_database('line')
    # You can check that the database exists
    if my_database.exists():
        print('SUCCESS!!')
    my_database = connection.create_database('next_in_line')

    # You can check that the database exists
    if my_database.exists():
        print('SUCCESS!!')
    '''
    return '<center><img src="https://static.wikia.nocookie.net/f377126c-7717-4026-aa5b-7ca887157442" alt="Hello There!"><br/><img src="https://media.makeameme.org/created/general-kenobi-5b18a9.jpg" alt="General Kenobi!"></center>'


# individually creates a customer instance
# Kevin made it. Ask Kevin for questions
@app.route('/addCustomer')
def addCustomer():
    name = request.args.get('name', None)
    phone = request.args.get('phone', None)

    database = connection['next_in_line']
    data = {
        'name': name,
        'phone': phone
    }

    response = instance.post_document(
        db='customer', document=customer_doc).get_result()

    return response

# a route to see all lines
# Kevin made it. Ask Kevin for questions


@ app.route('/getLines')
def getLines():

    response = instance.post_all_docs(
        db='line',
        include_docs=True,
        limit=10
    ).get_result()

    return response


# Send a request with {name:string} as a body param
# Code will be autogenerated here
@app.route('/createline', methods=['POST'])
def createLine():
    code = random.randint(1000, 9999)
    name = request.get_json()['name']
    session['line_operator'] = {"name": name, "code": code}

    database = connection['next_in_line']
    data = {
        'name': name,
        'code': code
    }
    response_document = database.create_document(data)
    print(response_document)

    return jsonify({"code": code})


@app.route('/join/<code>')
def join(code):
    # TODO All user to waiting line
    session['customer'] = {"name": "name", "code": code, "phone": phone}

    database = connection['next_in_line']
    data = {
        'name': name,
        'phone': phone
    }

    return redirect('/#/waiting')

# @app.route('/getlist/<code>')
# def getList(code):


def GenerateQRCode(url):
    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=10,
        border=4
    )

    qr.add_data(url)
    qr.make(fit=True)

    return qr.make_image(fill_color="black", back_color="white")


if __name__ == "__main__":
    app.run(debug=True)
